extends Node
class_name Enums

# the order of these is important as the enum value is used as an index.
enum KEY_DIRECTION { UP, LEFT, DOWN, RIGHT, ACTION, CANCEL, NAVIGATION };
enum KEY_DIRECTION_NEW { DIRECTION_UP, DIRECTION_LEFT, DIRECTION_DOWN, DIRECTION_RIGHT, BUTTON_UP, BUTTON_LEFT, BUTTON_DOWN, BUTTON_RIGHT }

enum BUTTON_MODE { WASD, ARROW, PS, XBOX, NINTENDO }
enum OPEN_MODE { CLOSE, OPEN, NONE }
enum CLIENT_CAM_STATE { OFF, BODY, HAPPY, POSITIVE, WORRIED, SPECIAL_1, SPECIAL_2, SPECIAL_3, SPECIAL_4 }
